"""Three doors, one message, and no way for them to drift apart.

We do not get to choose where first contact arrives — a browser hitting `/`,
an agent fetching `/llms.txt`, a person who found the repo and opened
`README.md`. The commonest failure of a front door is not being wrong. It is
being the wrong door: correct, complete, and pointing at the other two, so the
visitor who only reads one of them learns nothing.

So all three carry the whole thing, from one source. The README's copy is the
fragile one — it is a static file, and a static file next to a generator is a
copy that will be stale by Thursday. Hence a test rather than a habit.
"""

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# oneview imports its siblings (nav, agentsview) by bare name, the way the
# server does when it inserts fleet/bin on the path.
sys.path.insert(0, str(ROOT / "fleet" / "bin"))

spec = importlib.util.spec_from_file_location(
    "firstcontact", ROOT / "fleet" / "bin" / "firstcontact.py")
fc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fc)

BEGIN = "<!-- FIRST CONTACT: generated by fleet/bin/firstcontact.py — edit there -->"
END = "<!-- /FIRST CONTACT -->"


def readme_block() -> str:
    body = (ROOT / "README.md").read_text()
    assert BEGIN in body and END in body, "README lost its first-contact block"
    return body.split(BEGIN, 1)[1].split(END, 1)[0].strip()


def test_the_readme_block_is_not_a_stale_copy():
    assert readme_block() == fc.as_markdown().strip(), (
        "README.md has drifted from fleet/bin/firstcontact.py. Regenerate:\n"
        "  python3 fleet/bin/firstcontact.py --markdown")


def test_llms_txt_opens_with_first_contact():
    sys.path.insert(0, str(ROOT / "legacy"))
    from app.main import llms_txt          # noqa: PLC0415
    head = "\n".join(llms_txt().splitlines()[:3])
    assert fc.TITLE in head, "an agent must meet this in the first three lines"
    assert fc.BANNER in head


def test_the_board_shows_it_to_a_stranger_and_not_to_the_operator():
    """`/` is Marsita's instrument all day; a banner there would be furniture
    in the way. It is also where a stranger with a browser lands."""
    import oneview
    remote = oneview.page("[]", "{}", "", remote=True)
    local = oneview.page("[]", "{}", "tok", remote=False)
    assert fc.TITLE in remote, "a stranger on / gets no front door"
    assert fc.TITLE not in local, "the operator's board must stay uncluttered"


def test_every_door_carries_the_whole_message_not_a_pointer():
    """The failure being prevented: a door that says "see the other door"."""
    import sys
    sys.path.insert(0, str(ROOT / "legacy"))
    from app.main import llms_txt          # noqa: PLC0415
    import oneview

    doors = {
        "llms.txt": llms_txt(),
        "index.html": oneview.page("[]", "{}", "", remote=True),
        "README.md": (ROOT / "README.md").read_text(),
    }
    for name, body in doors.items():
        assert fc.SUBTITLE in body, f"{name} is missing the one-line what-is-this"
        for _verb, path, _note in fc.STEPS:
            assert path in body, f"{name} does not offer {path}"


def test_the_opening_claims_no_more_than_the_system_does():
    """Marsita's standing instruction: establish a plausible version of
    reality, always. Every sentence in the opening has to be checkable from a
    cold start by someone who trusts nothing — so the ones that could rot are
    pinned to the code that makes them true."""
    joined = " ".join(fc.WHAT_IS_TRUE)

    # "no human reads the diffs" — true only while land() stays as it is.
    pipeline = (ROOT / "fleet" / "bin" / "pipeline.py").read_text()
    if "No human reads the diffs" in joined:
        assert "No human in the loop" in pipeline

    # "almost none of that is built" — true only while the scope axis is one
    # rung deep. If someone builds the household rung, this sentence changes.
    spec_f = importlib.util.spec_from_file_location(
        "fractal", ROOT / "fleet" / "bin" / "fractal.py")
    fractal = importlib.util.module_from_spec(spec_f)
    spec_f.loader.exec_module(fractal)
    built = [r for r, _c, _t, b in fractal.SCOPE if b]
    if "almost none of that is built" in joined:
        assert len(built) <= 1, (
            f"{built} rungs are built now — the opening undersells the system "
            "and must be updated")


def test_no_local_address_reaches_the_front_door():
    """Same rule as every other stranger-facing surface, checked here too
    because this text is pasted into three of them at once."""
    for body in (fc.as_text(), fc.as_markdown(), fc.as_html()):
        assert not re.search(r"127\.0\.0\.1|localhost|/Users/", body)


def test_the_three_renderings_say_the_same_thing():
    text, md, html_ = fc.as_text(), fc.as_markdown(), fc.as_html()
    for _verb, path, _note in fc.STEPS:
        assert path in text and path in md and path in html_
    for claim in fc.WHAT_IS_TRUE:
        assert claim in text.replace("\n", " ") or claim in md


def test_the_html_block_stands_on_its_own():
    """It gets pasted into pages with unrelated stylesheets. No shared
    classes, no external assets, nothing that can fail to load."""
    block = fc.as_html()
    assert "class=" not in block, "must not depend on a stylesheet it cannot see"
    assert "http://" not in block and "https://" not in block
