"""Three doors, one message, and no way for them to drift apart.

We do not get to choose where first contact arrives — a browser hitting `/`,
an agent fetching `/llms.txt`, a person who found the repo and opened
`README.md`. The commonest failure of a front door is not being wrong. It is
being the wrong door: correct, complete, and pointing at the other two, so the
visitor who only reads one of them learns nothing.

So all three carry the whole thing, from one source. The README's copy is the
fragile one — it is a static file, and a static file next to a generator is a
copy that will be stale by Thursday. Hence a test rather than a habit.
"""

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# oneview imports its siblings (nav, agentsview) by bare name, the way the
# server does when it inserts fleet/bin on the path.
sys.path.insert(0, str(ROOT / "fleet" / "bin"))

spec = importlib.util.spec_from_file_location(
    "firstcontact", ROOT / "fleet" / "bin" / "firstcontact.py")
fc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fc)

BEGIN = "<!-- FIRST CONTACT: generated by fleet/bin/firstcontact.py — edit there -->"
END = "<!-- /FIRST CONTACT -->"


def readme_block() -> str:
    body = (ROOT / "README.md").read_text()
    assert BEGIN in body and END in body, "README lost its first-contact block"
    return body.split(BEGIN, 1)[1].split(END, 1)[0].strip()


def test_the_readme_block_is_not_a_stale_copy():
    assert readme_block() == fc.as_markdown().strip(), (
        "README.md has drifted from fleet/bin/firstcontact.py. Regenerate:\n"
        "  python3 fleet/bin/firstcontact.py --markdown")


def test_llms_txt_opens_with_first_contact():
    sys.path.insert(0, str(ROOT / "legacy"))
    from app.main import llms_txt          # noqa: PLC0415
    head = "\n".join(llms_txt().splitlines()[:3])
    assert fc.TITLE in head, "an agent must meet this in the first three lines"
    assert fc.BANNER in head


def test_the_board_shows_it_to_a_stranger_and_not_to_the_operator():
    """`/` is Marsita's instrument all day; a banner there would be furniture
    in the way. It is also where a stranger with a browser lands."""
    import oneview
    remote = oneview.page("[]", "{}", "", remote=True)
    local = oneview.page("[]", "{}", "tok", remote=False)
    assert fc.TITLE in remote, "a stranger on / gets no front door"
    assert fc.TITLE not in local, "the operator's board must stay uncluttered"


def test_every_door_carries_the_whole_message_not_a_pointer():
    """The failure being prevented: a door that says "see the other door"."""
    import sys
    sys.path.insert(0, str(ROOT / "legacy"))
    from app.main import llms_txt          # noqa: PLC0415
    import oneview

    doors = {
        "llms.txt": llms_txt(),
        "index.html": oneview.page("[]", "{}", "", remote=True),
        "README.md": (ROOT / "README.md").read_text(),
    }
    for name, body in doors.items():
        assert fc.SUBTITLE in body, f"{name} is missing the one-line what-is-this"
        for _verb, path, _note in fc.STEPS:
            assert path in body, f"{name} does not offer {path}"
        assert "python3 fleet/bin/brief.py" in body, \
            f"{name} does not state the repository starting command"


def test_the_opening_claims_no_more_than_the_system_does():
    """Marsita's standing instruction: establish a plausible version of
    reality, always. Every sentence in the opening has to be checkable from a
    cold start by someone who trusts nothing — so the ones that could rot are
    pinned to the code that makes them true."""
    joined = " ".join(fc.WHAT_IS_TRUE)

    # "no human reads the diffs" — true only while land() stays as it is.
    pipeline = (ROOT / "fleet" / "bin" / "pipeline.py").read_text()
    if "No human reads the diffs" in joined:
        assert "No human in the loop" in pipeline

    # "almost none of that is built" — true only while the scope axis is one
    # rung deep. If someone builds the household rung, this sentence changes.
    spec_f = importlib.util.spec_from_file_location(
        "fractal", ROOT / "fleet" / "bin" / "fractal.py")
    fractal = importlib.util.module_from_spec(spec_f)
    spec_f.loader.exec_module(fractal)
    built = [r for r, _c, _t, b in fractal.SCOPE if b]
    if "almost none of that is built" in joined:
        assert len(built) <= 1, (
            f"{built} rungs are built now — the opening undersells the system "
            "and must be updated")


def test_no_local_address_reaches_the_front_door():
    """Same rule as every other stranger-facing surface, checked here too
    because this text is pasted into three of them at once."""
    for body in (fc.as_text(), fc.as_markdown(), fc.as_html()):
        assert not re.search(r"127\.0\.0\.1|localhost|/Users/", body)


def test_the_three_renderings_say_the_same_thing():
    text, md, html_ = fc.as_text(), fc.as_markdown(), fc.as_html()
    for _verb, path, _note in fc.STEPS:
        assert path in text and path in md and path in html_
    for claim in fc.WHAT_IS_TRUE:
        assert claim in text.replace("\n", " ") or claim in md


def test_the_html_block_stands_on_its_own():
    """It gets pasted into pages with unrelated stylesheets. No shared
    classes, no external assets, nothing that can fail to load."""
    block = fc.as_html()
    assert "class=" not in block, "must not depend on a stylesheet it cannot see"
    assert "http://" not in block and "https://" not in block


def test_the_opening_stays_within_ten_sentences():
    """Marsita, 2026-08-25: "we could keep 10 sentences how to describe it."

    A cap held by intention is a cap that lasts until the next good idea. Every
    future edit will feel like it earns one more sentence, and the page a
    stranger meets is the one place where that is always false."""
    got = fc.sentences()
    assert len(got) <= fc.SENTENCE_BUDGET, (
        f"first contact is {len(got)} sentences, budget is "
        f"{fc.SENTENCE_BUDGET}:\n" + "\n".join(f"  {i+1}. {x}"
                                               for i, x in enumerate(got)))


def test_the_opening_is_species_agnostic():
    """It does not know who is reading it. An agent addressed as a tool
    behaves like one; a person addressed as a user reads past the part that
    mattered. So the text names more than one kind of reader and commits to
    none."""
    body = " ".join(fc.WHAT_IS_TRUE) + " " + fc.SUBTITLE
    assert "conscious forms of life" in body
    low = body.lower()
    assert "human" in low and "agent" in low, \
        "the reader may be either, and the text has to say so"


def test_the_opening_leads_with_what_runs():
    """An earlier draft opened by listing what is NOT built, beside a sentence
    about the fleet — so it read as "almost none of this project exists" when
    sixty modules and six hundred tests do. Ambition lives at /scale."""
    first = fc.WHAT_IS_TRUE[0].lower()
    assert "runs" in first or "running" in first
    joined = " ".join(fc.WHAT_IS_TRUE).lower()
    for undersell in ("almost none", "not built", "nothing is built",
                      "barely", "hardly any"):
        assert undersell not in joined, (
            f"the opening undersells the system with {undersell!r}; "
            "the empty rungs belong at /scale")


def test_the_doors_come_before_the_explanation():
    """A reader should be able to act before they have finished reading.

    This is load-bearing rather than stylistic: when the opening was rewritten
    to ten sentences, the prose pushed READ/LOOK/JOIN off the first screen and
    the front-screen test caught it. Ordering the steps first is what fixed it,
    so the order needs a test of its own or the next rewrite loses it again."""
    for rendering in (fc.as_text(), fc.as_markdown(), fc.as_html()):
        first_step = rendering.index(fc.STEPS[0][1])
        first_prose = rendering.index(fc.WHAT_IS_TRUE[0][:40])
        assert first_step < first_prose, \
            "the doors must appear before the paragraphs explaining them"


def test_the_readme_rendering_has_no_relative_links():
    """README.md is read on GitHub, in editors, and by `cat`. A relative link
    like [/boot](/boot) resolves against github.com there and 404s for every
    reader who arrived through the repo door — the same shape as the
    127.0.0.1 instruction already in the brainfarts log: a path that only
    works from the seat the author was sitting in.

    Paths stay as code spans, and the closing line says what to resolve them
    against."""
    md = fc.as_markdown()
    assert not re.search(r"\]\(/[a-z]", md), \
        "relative markdown links break wherever the README is actually read"
    assert "relative" in fc.CLOSING.lower(), \
        "a reader with no host in hand needs telling what these resolve against"


def test_boot_is_not_a_dead_end():
    """/boot is step one of READ / LOOK / JOIN. A first step that names no
    second step is a dead end with good manners."""
    sys.path.insert(0, str(ROOT / "legacy"))
    from app.main import boot              # noqa: PLC0415
    body = boot()
    for onward in ("/map", "/join", "/llms.txt"):
        assert onward in body, f"/boot never mentions {onward}"


def test_boot_uses_the_same_operating_contract_as_local_agents():
    sys.path.insert(0, str(ROOT / "legacy"))
    from app.main import boot              # noqa: PLC0415
    spec_c = importlib.util.spec_from_file_location(
        "agentcontract", ROOT / "fleet" / "bin" / "agentcontract.py")
    contract = importlib.util.module_from_spec(spec_c)
    spec_c.loader.exec_module(contract)
    body = boot()
    for rule in contract.RULES:
        assert rule in body


def test_a_get_on_the_join_endpoint_admits_the_door_exists():
    """404 tells a probing agent the endpoint is not there. It is there; it
    takes POST. /api/pair already answers 405 and the two sit side by side in
    the same manifest."""
    src = (ROOT / "fleet" / "bin" / "fleet.py").read_text()
    block = src.split('if path == "/api/trust/join":', 1)
    assert len(block) > 1, "no GET handler for /api/trust/join"
    head = block[1][:600]
    assert "405" in head and "Allow" in head
